CREATE DATABASE IF NOT EXISTS auto_print CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'auto_print'@'localhost' IDENTIFIED BY 'CHANGE_THIS';
GRANT ALL PRIVILEGES ON auto_print.* TO 'auto_print'@'localhost';
FLUSH PRIVILEGES;
USE auto_print;
CREATE TABLE IF NOT EXISTS clients (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  upi_id VARCHAR(160) DEFAULT '',
  upi_number VARCHAR(40) DEFAULT '',
  qr_text TEXT,
  enabled TINYINT(1) DEFAULT 1,
  online TINYINT(1) DEFAULT 0,
  last_seen DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS jobs (
  id VARCHAR(64) PRIMARY KEY,
  client_id VARCHAR(64) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  stored_path TEXT NOT NULL,
  print_type VARCHAR(40) DEFAULT 'B/W',
  paper VARCHAR(40) DEFAULT 'A4',
  copies INT DEFAULT 1,
  status VARCHAR(40) DEFAULT 'queued',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(client_id), INDEX(status),
  CONSTRAINT fk_jobs_client FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE CASCADE
);
